### ISSUE TITLE
Missing Information For:hs.webster.k12.mo.us

### ISSUE THREAD

**Issue by 6ay6irl3817** [xorprojects/We-LGBT#15]
Webster groves high school (and all of the Webster school district) hate lgbt people, i  hate that i must attend their schools. i'm gay and if other students make fun of me or slap me it is seen as 'Justice' .

**Comment by crutchcorn** [comment]
Seen as justice by who? Has there been public comment regarding their views on LBGT? I was bullied extremely in my highschool and yet I don't think that's what the school would have wanted - despite them not doing anything against it. You know what I'm saying?

**Comment by danielhickman** [comment]
I apologize greatly for how you've been treated, but I don't think this is enough to change to their stance.
