### ISSUE TITLE
Missing Information For:westvancouverhomewatch.com

### ISSUE THREAD

**Issue by Christervcr** [xorprojects/We-LGBT#20]
- Name: 
- Description:

**Comment by danielhickman** [comment]
I see you're the owner of this business. What's your position on LGBT rights?

**Comment by Christervcr** [comment]
It should be the same rights for LGBT as for everyone else.

**Comment by crutchcorn** [comment]
👏👏👏 You sir, are a gentleman and a scholar. Just to jump in here and
help Daniel out; are there any comments or anything that you'd like to add
regarding your support if you are added to the whitelist on WeLGBT?
