### ISSUE TITLE
Missing Information For: eheadspace.org.au

### ISSUE THREAD

**Issue by Doofitator** [xorprojects/We-LGBT#26]
- Name of Company: Headspace Australia
- Description: A mental heath online help website

**Comment by danielhickman** [comment]
Is this site supportive? It's GEOIP blocked for the United States.

**Comment by Doofitator** [comment]
Its an Australian site, so its understandable that its blocked for the US.
It is a mental health help site, and has helped myself and some of my friends with LGBT related issues that have been messing us over VIA it's online chat. The councillors/therapists are very understanding. It is very accepting.
